### ISSUE TITLE
Security credential key missing

### ISSUE THREAD

**Issue by cngeru** [newtonmunene99/mpesa-api#11]
Does the lib generate it or isn't it compulsory ?
Also how (Where) do I get the initiator Name?

**Comment by newtonmunene99** [comment]
Hi @cngeru , could you please provide a more detailed issue. Please include the method you were trying to use, maybe code sample if possible.

**Comment by newtonmunene99** [comment]
Security credential is generated by the library.
You can get Initiator Name from here https://developer.safaricom.co.ke/test_credentials

**Comment by cngeru** [comment]
what about in production...how do I get the security credential.

**Comment by newtonmunene99** [comment]
As I mentioned, you don't need to pass security credential, it's generated by the library based on the credentials passed when initializing

**Comment by cngeru** [comment]
Meant to ask about the Initiator name... My bad

**Comment by newtonmunene99** [comment]
You provide this name When applying for a bulk payments shortcode from Safaricom. If Safaricom has already issued you with your shortcode you should also have this. 

Please take a look at this for more detailed info.
https://peternjeru.co.ke/safdaraja/ui/#b2c_tutorial

**Comment by cngeru** [comment]
Thank you... Can you create a slack channel please... For people to ask queries. Instead of having to create issues.
Thank you again

**Comment by newtonmunene99** [comment]
The module is just a wrapper around the daraja api. It wouldn't be practical to create a channel when there exists such for the api. Here's a existing Telegram channel where you can get help concerning the API . https://t.me/payments_api
