### ISSUE TITLE
version mismatch npm i gets version 2.2.0 , however latest version is 2.3.1

### ISSUE THREAD

**Issue by nelsonBlack** [newtonmunene99/mpesa-api#15]
npm i mpesa-api gets a previous version 2.2.0 , however latest version is 2.3.1 

```
$ npm view mpesa-api

 mpesa-api@2.2.0 | MIT | deps: 1 | versions: 8
An NPM Module built with NodeJs to help you with M-Pesa Daraja API calls.
https://github.com/newtonmunene99/mpesa-api/

keywords: mpesa, nodejs, node, mobile money, money

dist
.tarball: https://registry.npmjs.org/mpesa-api/-/mpesa-api-2.2.0.tgz
.shasum: 28574429cdbb6cd34b530e77c41f2726d4739116
.integrity: sha512-004ASyvfITbj5DkzwgbWw9ayVV5+qzR6pQmqdm+kJp+AXV5v1co4lS1o0u8SHoqG6AeXXf2cbylTUNeZ2ltMOw==
.unpackedSize: 66.1 kB

dependencies:
axios: ^0.19.0

maintainers:
- newtonmunene99 <newtonmunene99@gmail.com>

dist-tags:
latest: 2.2.0```

**Comment by newtonmunene99** [comment]
The changes haven't yet reflected on npm. It's taking longer than usual.
 Let's give it a few hours

**Comment by nelsonBlack** [comment]
okay , thanks for the swift response

**Comment by newtonmunene99** [comment]
In the meantime you can use https://github.com/newtonmunene99/mpesa-api/packages/57741

**Comment by nelsonBlack** [comment]
thanks a bunch

**Comment by nelsonBlack** [comment]
kindly check the package , trying to install brings 

> In the meantime you can use https://github.com/newtonmunene99/mpesa-api/packages/57741

`npm install @newtonmunene99/mpesa-api@2.3.1 --save

npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@newtonmunene99%2fmpesa-api - Not found
npm ERR! 404 
npm ERR! 404  '@newtonmunene99/mpesa-api@2.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)`

**Comment by newtonmunene99** [comment]
Sorry about that, you have to specify to npm to use the GitHub package registry when installing. You can now install from npm https://www.npmjs.com/package/mpesa-api
