### ISSUE TITLE
B2C API bug :- "Bad Request - Invalid InitiatorName"

### ISSUE THREAD

**Issue by mulama77** [newtonmunene99/mpesa-api#8]
On your mpesa-api, while invoking the B2C API in the sandbox, I am getting the below error 

`"data":{"requestId":"3911-7748949-1","errorCode":"400.002.02","errorMessage":"Bad Request - Invalid InitiatorName"},"service":"user-service"}
`

even though the InitiatorName is part of the parameters in the code. i.e.

But when checking the payload in the logs, it's actually missing i.e
`"data":"{\"SecurityCredential\":\"lAqo9GH\",\"CommandID\":\"BusinessPayment\",\"Amount\":\"10\",\"PartyA\":600638,\"PartyB\":\"2547xxxxxxxx\",\"Remarks\":\"DriverPayment\",\"QueueTimeOutURL\":\"https://test.com/api/callback.php\",\"ResultURL\":\"https://test.com/api/callback.php\",\"Occasion\":\"account\"}"`

```
  // invoking the mpesa api
  mpesa
  .b2c({
    InitiatorName: Constants.initiatorName,
    Amount: req.body.Amount,
    PartyA: Constants.PaybillB2C,
    PartyB: req.body.PhoneNumber,
    QueueTimeOutURL: Constants.QueueTimeOutURL,
    ResultURL: Constants.ResultURL,
    CommandID: Constants.CommandID,
    Occassion: Constants.Occassion,
    Remarks: req.body.TransactionDesc
  })
```

**Comment by nzauabraham** [comment]
Can also be caused by not having "Content-Type: application/json" in your headers
